export interface StageConfig {
  level: number;
  name: string;
  xOffset: number;
}

export const STAGE_CONFIGS: StageConfig[] = [
  // Chapter 1 ~ 5 ( 기존 1 ~ 25 완만하고 예쁜 지그재그 재정렬 )
  { level: 1, name: "알록달록 연습장", xOffset: 0 },
  { level: 2, name: "앵두 밭", xOffset: -0.55 },
  { level: 3, name: "초록 풀숲", xOffset: 0.6 },
  { level: 4, name: "무지개 언덕", xOffset: -0.45 },
  { level: 5, name: "별빛 호수", xOffset: 0.5 },
  { level: 6, name: "구름 정원", xOffset: -0.65 },
  { level: 7, name: "반짝 별길", xOffset: 0.55 },
  { level: 8, name: "솜사탕 동산", xOffset: -0.4 },
  { level: 9, name: "과자 성", xOffset: 0.6 },
  { level: 10, name: "무지개 성단", xOffset: -0.5 },
  { level: 11, name: "비눗방울 마을", xOffset: 0.45 },
  { level: 12, name: "낮잠 구름", xOffset: -0.6 },
  { level: 13, name: "딸기 폭포", xOffset: 0.55 },
  { level: 14, name: "은하수 길", xOffset: -0.45 },
  { level: 15, name: "젤리 왕국", xOffset: 0.6 },
  { level: 16, name: "새싹 들판", xOffset: -0.5 },
  { level: 17, name: "노을빛 언덕", xOffset: 0.65 },
  { level: 18, name: "꿀벌 목장", xOffset: -0.4 },
  { level: 19, name: "이슬 맺힌 풀잎", xOffset: 0.5 },
  { level: 20, name: "바람개비 동산", xOffset: -0.65 },
  { level: 21, name: "달빛 오아시스", xOffset: 0.45 },
  { level: 22, name: "별사탕 공장", xOffset: -0.55 },
  { level: 23, name: "오색빛깔 성", xOffset: 0.6 },
  { level: 24, name: "하늘 정원", xOffset: -0.35 },
  { level: 25, name: "해님 대왕의 궁전", xOffset: 0.3 },

  // Chapter 6 확장 영역 ( Level 26 ~ 50 )
  { level: 26, name: "민들레 씨앗 언덕", xOffset: -0.6 },
  { level: 27, name: "알록달록 풍선 탑", xOffset: 0.55 },
  { level: 28, name: "보석 결정 동굴", xOffset: -0.45 },
  { level: 29, name: "파도 소리 해변", xOffset: 0.65 },
  { level: 30, name: "무지개 물고기 쉼터", xOffset: -0.3 },
  { level: 31, name: "장난감 태엽 공장", xOffset: 0.4 },
  { level: 32, name: "도토리 숲속 오솔길", xOffset: -0.6 },
  { level: 33, name: "단풍잎 카펫 길", xOffset: 0.5 },
  { level: 34, name: "하늘빛 소라껍데기", xOffset: -0.45 },
  { level: 35, name: "반딧불이 밤하늘", xOffset: 0.6 },
  { level: 36, name: "초콜릿 분수 광장", xOffset: -0.55 },
  { level: 37, name: "마법 스케치북", xOffset: 0.45 },
  { level: 38, name: "거울 호수 정원", xOffset: -0.65 },
  { level: 39, name: "우주선 승강장", xOffset: 0.35 },
  { level: 40, name: "토성과 고리 정글", xOffset: -0.5 },
  { level: 41, name: "달콤 쿠키 산맥", xOffset: 0.6 },
  { level: 42, name: "시계태엽 타워", xOffset: -0.4 },
  { level: 43, name: "황금 열쇠 광산", xOffset: 0.55 },
  { level: 44, name: "수수께끼 미로 숲", xOffset: -0.6 },
  { level: 45, name: "오로라 언덕", xOffset: 0.45 },
  { level: 46, name: "수경 재배 숲", xOffset: -0.5 },
  { level: 47, name: "크리스탈 성곽", xOffset: 0.65 },
  { level: 48, name: "꿈꾸는 유성우 길", xOffset: -0.35 },
  { level: 49, name: "마법사의 비밀 서재", xOffset: 0.5 },
  { level: 50, name: "최종 마법의 왕국", xOffset: 0 },
];
